Resources:
  Admins:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Admins
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  PowerUsers:
    Type: AWS::IAM::Group
    Properties:
      GroupName: PowerUsers
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonRoute53DomainsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchEventsFullAccess
        - arn:aws:iam::aws:policy/AWSCloudTrailFullAccess
        - arn:aws:iam::aws:policy/job-function/Billing
        - Fn::ImportValue: iam-policies-${self:provider.stage}-CloudFormationFullAccessArn

  Users:
    Type: AWS::IAM::Group
    Properties:
      GroupName: Users
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMSelfManageServiceSpecificCredentials
        - arn:aws:iam::aws:policy/IAMUserChangePassword
        - arn:aws:iam::aws:policy/IAMUserSSHKeys

  DevAdmins:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DevAdmins
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessDevAdminPolicyArn

  DevUsers:
    Type: AWS::IAM::Group
    Properties:
      GroupName: DevUsers
      ManagedPolicyArns:
        - Fn::ImportValue: iam-policies-${self:provider.stage}-OrganizationAccountAccessDevUsersPolicyArn
